name: Python Application

# Controls when the workflow will run
on:
  push:
    branches: [ main ]  # You can change the branch name as per your repo setup
  pull_request:
    branches: [ main ]

# Set the job's environment to Python and Ubuntu
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out repository code
      uses: actions/checkout@v2

    # Set up Python 3.10 (or the version required for your project)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Install dependencies defined in your `Makefile`
    - name: Install Dependencies
      run: make install

    # Run your server, then let it sleep for a few seconds to ensure the server starts properly
    - name: Run the application
      run: |
        make run &
        sleep 5  # Adjust this time as needed to ensure the server starts up

    # Optionally, you can add more commands here to simulate further testing
