name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository code
      uses: actions/checkout@v2

    # Step 2: Set up Python (explicitly install Python version)
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Step 3: Install dependencies using the Makefile
    - name: Install Dependencies
      run: |
        python3 -m venv venv  # Manually create the virtual environment
        . venv/bin/activate    # Activate the virtual environment
        make install           # Install dependencies from the Makefile

    # Step 4: Run the server (ensure enough time for server startup)
    - name: Run the application
      run: |
        . venv/bin/activate    # Activate the virtual environment
        make run &             # Start the application
        sleep 5                # Wait to ensure the server has time to start
